// Generated by LiveScript 1.3.0
(function(){
  var fs, path, user, board, reset, verify;
  fs = require('fs');
  path = require('path');
  user = require('./user');
  board = require('./board');
  reset = require('./auth/reset');
  verify = require('./auth/verify');
  module.exports = function(engine, io){
    user(engine, io);
    reset(engine, io);
    verify(engine, io);
    return board(engine, io);
  };
}).call(this);
